# Similar to ReplicaSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: httpd-container
        image: httpd:alpine3.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
  replicas: 6
  selector: 
    matchLabels:
      type: front-end

