# Similar to ReplicaSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bika-myapp-deploy
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: bika-nginx-container
        image: nginx:stable-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
  replicas: 3
  selector: 
    matchLabels:
      app: nginx

