apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: backend
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"